- wildlifecompliance/components/sanction_outcome/api.py
- wildlifecompliance/helpers.py
- Remediation can only be modified if submitter is same as offender and
status is Open.
> graeme-enhancement

- wildlifecompliance/frontend/wildlifecompliance/src/components/common/renderer_block.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/date-field.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/expander_table.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/file.vue
- wildlifecompliance/frontend/wildlifecompliance/src/scss/forms/expander_table.scss
> Ap working

- wildlifecompliance/components/licences/utils.py
- wildlifecompliance/frontend/wildlifecompliance/src/components/common/renderer_block.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/checkbox.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/date-field.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/expander_table.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/file.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/group_species.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/label.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/richtext.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/select.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/select_filtered.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/select_species.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/table.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/text-area.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/text.vue
- help text url icon now placed correctly with long question labels
- carriage return in question labels working
> WLC ticket 150493 further changes requested

- .devcontainer/devcontainer.json
- wildlifecompliance/frontend/wildlifecompliance/src/components/external/returns/enter_return_sheet_entry.vue
Improvements include
- Mandated 'number' datatype in the Quantity field when creating a new entry
- Mandated 'Activity' entry when updating or entering new entry to the return sheet
- Added logic for 'out' qtys to readjust totals
Note: Prod incidents would require fixing data through database manipulation
> improvements to return sheet

- wildlifecompliance/frontend/wildlifecompliance/src/components/external/returns/enter_return_sheet_entry.vue
Pending two more bugs pointed out by Norm
- Activity Date bug upon Save & Continue
- Remove default specie for first time license holders when creating a new return sheet
> added FE logic to avoid negative numbers in total

- wildlifecompliance/frontend/wildlifecompliance/src/components/external/returns/enter_return_sheet.vue
Bug: First time a licence holder goes into their Return section, it’s pre-filled with a random species from the regulated species list.
This is now resolved with the below changes
> improved logic for first entry of specie selection

- wildlifecompliance/views.py
Non-internal users can no longer access the management command page
> Management Command Fix

- Dockerfile
Dockerfile changed to get the health script
> Kubernetes health check

- wildlifecompliance/components/inspection/api.py
- wildlifecompliance/frontend/wildlifecompliance/src/components/internal/inspection/inspection_dashboard.vue
Only members of at least one inspection officer or manager group will be presented with the "new inspection" button on the inspection dashboard.
> New Inspection Button Auth

- wildlifecompliance/helpers.py
- wildlifecompliance/templates/wildlifecompliance/index.html
- wildlifecompliance/views.py
> Updated for auth2 login (/ssologin)

- wildlifecompliance/components/users/serializers.py
- wildlifecompliance/frontend/wildlifecompliance/src/components/user/manage_my_user_details.vue
- wildlifecompliance/templates/wildlifecompliance/user_profile.html
Disabled first name and last name editing for accounts, provided link to sso/setting.
> Restrict user name edit

- requirements.txt
Packages updates to latest compatible versions.
Updated packages include:
- gunicorn
- djangorestframework
- djangorestframework-gis
- wheel
- urllib3
- requests
- numpy
- idna
- setuptools
> Python Package Updates

- wildlifecompliance/components/applications/api.py
- wildlifecompliance/components/applications/serializers.py
- wildlifecompliance/context_processors.py
- wildlifecompliance/helpers.py
- wildlifecompliance/settings.py
- wildlifecompliance/templates/wildlifecompliance/base.html
- wildlifecompliance/templates/wildlifecompliance/dash/index.html
- wildlifecompliance/templatetags/users.py
Ensure that non-officer users (even if internal) must have the respective officer or readonly user auth to access internal dashboards client-side.
Includes a context_processors.
> Auth Adjustments + Context Processor

- wildlifecompliance/components/applications/serializers.py
- wildlifecompliance/components/returns/serializers.py
Applied some serializer fixes to issues that had caused returns viewset to fail.
> Returns Fix

- wildlifecompliance/components/applications/api.py
- wildlifecompliance/components/licences/utils.py
- wildlifecompliance/components/users/api.py
- wildlifecompliance/components/users/serializers.py
- Changed date format display on account management for legal dob
- Adjusted search function to search by full name (both account and legal)
- Adjusted minimum age check function to account for and prioritise legal dob
- Added age check function to server-side application submit (previously only client-side check)
> Minor Adjustments

- wildlifecompliance/frontend/wildlifecompliance/src/components/user/manage_my_user_details.vue
- wildlifecompliance/templates/wildlifecompliance/user_profile.html
SSO setting url now sets back url to current url (instead of fixed back in env var)
> SSO setting url dynamic

- wildlifecompliance/frontend/wildlifecompliance/src/components/user/manage_my_user_details.vue
- wildlifecompliance/templates/wildlifecompliance/user_profile.html
Changes will not update until your next login.
> Changes will not update until your next login

- wildlifecompliance/frontend/wildlifecompliance/package-lock.json
- wildlifecompliance/frontend/wildlifecompliance/package.json
- wildlifecompliance/frontend/wildlifecompliance/src/components/forms/richtext.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/internal/applications/application_issuance.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/internal/applications/proposed_issuance.vue
Updated ckeditor4-vue for to latest available (non-commercial) version and suppressed warning display.
> CKEditor Warning

- wildlifecompliance/components/main/api.py
Added create functions for schema viewsets with officer auth checks
> Create functions for Schema viewsets

- segregation_steps.md
- wildlifecompliance/frontend/wildlifecompliance/src/components/external/organisations/manage.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/internal/applications/application.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/internal/assignment.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/internal/organisations/access.vue
- wildlifecompliance/frontend/wildlifecompliance/src/components/user/manage_organisations.vue
- wildlifecompliance/frontend/wildlifecompliance/src/router/index.js
- wildlifecompliance/frontend/wildlifecompliance/src/store/modules/inspection.js
- wildlifecompliance/frontend/wildlifecompliance/src/store/modules/legal_case.js
- wildlifecompliance/frontend/wildlifecompliance/src/store/modules/offence.js
- wildlifecompliance/frontend/wildlifecompliance/src/store/modules/sanction_outcome.js
- wildlifecompliance/settings.py
- wildlifecompliance/templates/ledgerui/accounts_base_b5.html
- wildlifecompliance/templates/wildlifecompliance/base.html
- wildlifecompliance/urls.py
Fixed various JS errors
Fixed org request issues
Updated segregation steps
> Ledger segregation work

- requirements.txt
- wildlifecompliance/components/applications/admin.py
- wildlifecompliance/components/applications/models.py
- wildlifecompliance/components/applications/services.py
- wildlifecompliance/components/artifact/models.py
- wildlifecompliance/components/call_email/models.py
- wildlifecompliance/components/inspection/models.py
- wildlifecompliance/components/legal_case/models.py
- wildlifecompliance/components/licences/admin.py
- wildlifecompliance/components/licences/models.py
- wildlifecompliance/components/main/models.py
- wildlifecompliance/components/main/utils.py
- wildlifecompliance/components/offence/models.py
- wildlifecompliance/components/organisations/models.py
- wildlifecompliance/components/returns/models.py
- wildlifecompliance/components/sanction_outcome/models.py
- wildlifecompliance/components/sanction_outcome_due/models.py
- wildlifecompliance/components/users/models.py
- wildlifecompliance/ordered_model.py
Include some missing modules to requirements.txt
Upgrade to django 5.2 (and updated related required packages)
Added (and modified) sanitise mixin for removing html and/or scripts from saved strings/json fields
Sanitise mixin has been tested on most models but more testing should be followed through on to ensure every applicable case works as expected
Some changes RE handling RichTextField exceptions and JSONFields in particular should be tested
(Changes will also be replicated for MooringLicensing where initial efforts had been conducted)
> Ledger segregation
